services:
  - type: web
    name: crm-dashboard
    env: node
    buildCommand: npm run install-backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000